version: "3"
services:
  server_tcp:
    # image: ms-apprein-js:1.0
    build:
      #     dockerfile: ./buildDocker/local.DockerFile
      context: .
    ports:
      - 4040:4040
    hostname: server_tcp
    restart: always
    volumes:
      # -   ./:/usr/local/nodeapps/
      - /usr/local/volumes/server_tcp:/root/.pm2/logs

    # command: pm2-runtime server.config.js --env development
    command: pm2-runtime server.config.js
